export const characters = [
  {
    name: 'Albedo',
    rarity: 5,
    weapon: 'Sword',
    element: 'Geo',
  },
  {
    name: 'Aloy',
    rarity: 5,
    weapon: 'Bow',
    element: 'Cryo',
  },
  {
    name: 'Amber',
    rarity: 4,
    weapon: 'Bow',
    element: 'Pyro',
  },
  {
    name: 'Ayaka',
    rarity: 5,
    weapon: 'Sword',
    element: 'Cryo',
  },
  {
    name: 'Barbara',
    rarity: 4,
    weapon: 'Catalyst',
    element: 'Hydro',
  },
  {
    name: 'Beidou',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Electro',
  },
  {
    name: 'Bennett',
    rarity: 4,
    weapon: 'Sword',
    element: 'Pyro',
  },
  {
    name: 'Chongyun',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Cryo',
  },
  {
    name: 'Diluc',
    rarity: 5,
    weapon: 'Claymore',
    element: 'Pyro',
  },
  {
    name: 'Diona',
    rarity: 4,
    weapon: 'Bow',
    element: 'Cryo',
  },
  {
    name: 'Eula',
    rarity: 5,
    weapon: 'Claymore',
    element: 'Cryo',
  },
  {
    name: 'Fischl',
    rarity: 4,
    weapon: 'Bow',
    element: 'Electro',
  },
  {
    name: 'Ganyu',
    rarity: 5,
    weapon: 'Bow',
    element: 'Cryo',
  },
  {
    name: 'Gorou',
    rarity: 4,
    weapon: 'Bow',
    element: 'Geo',
  },
  {
    name: 'Hu Tao',
    rarity: 5,
    weapon: 'Polearm',
    element: 'Pyro',
  },
  {
    name: 'Itto',
    rarity: 5,
    weapon: 'Claymore',
    element: 'Geo',
  },
  {
    name: 'Jean',
    rarity: 5,
    weapon: 'Sword',
    element: 'Anemo',
  },
  {
    name: 'Kaeya',
    rarity: 4,
    weapon: 'Sword',
    element: 'Cryo',
  },
  {
    name: 'Kazuha',
    rarity: 5,
    weapon: 'Sword',
    element: 'Anemo',
  },
  {
    name: 'Keqing',
    rarity: 5,
    weapon: 'Sword',
    element: 'Electro',
  },
  {
    name: 'Klee',
    rarity: 5,
    weapon: 'Catalyst',
    element: 'Pyro',
  },
  {
    name: 'Kokomi',
    rarity: 5,
    weapon: 'Catalyst',
    element: 'Hydro',
  },
  {
    name: 'Lisa',
    rarity: 4,
    weapon: 'Catalyst',
    element: 'Electro',
  },
  {
    name: 'Yae Miko',
    rarity: 5,
    weapon: 'Catalyst',
    element: 'Electro',
  },
  {
    name: 'Mona',
    rarity: 5,
    weapon: 'Catalyst',
    element: 'Hydro',
  },
  {
    name: 'Ningguang',
    rarity: 4,
    weapon: 'Catalyst',
    element: 'Geo',
  },
  {
    id: 'noelle',
    name: 'Noelle',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Geo',
  },
  {
    id: 'qiqi',
    name: 'Qiqi',
    rarity: 5,
    weapon: 'Sword',
    element: 'Cryo',
  },
  {
    name: 'Razor',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Electro',
  },
  {
    name: 'Rosaria',
    rarity: 4,
    weapon: 'Polearm',
    element: 'Cryo',
  },
  {
    name: 'Sara',
    rarity: 4,
    weapon: 'Bow',
    element: 'Electro',
  },
  {
    name: 'Sayu',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Anemo',
  },
  {
    name: 'Shenhe',
    rarity: 5,
    weapon: 'Polearm',
    element: 'Cryo',
  },
  {
    name: 'Shogun',
    rarity: 5,
    weapon: 'Polearm',
    element: 'Electro',
  },
  {
    name: 'Sucrose',
    rarity: 4,
    weapon: 'Catalyst',
    element: 'Anemo',
  },
  {
    name: 'Tartaglia',
    rarity: 5,
    weapon: 'Bow',
    element: 'Hydro',
  },
  {
    name: 'Thoma',
    rarity: 4,
    weapon: 'Polearm',
    element: 'Pyro',
  },
  {
    name: 'Traveler',
    rarity: 5,
    weapon: 'Sword',
    element: 'Anemo',
  },
  {
    name: 'Traveler',
    rarity: 5,
    weapon: 'Sword',
    element: 'Geo',
  },
  {
    name: 'Traveler',
    rarity: 5,
    weapon: 'Sword',
    element: 'Electro',
  },
  {
    name: 'Venti',
    rarity: 5,
    weapon: 'Bow',
    element: 'Anemo',
  },
  {
    name: 'Xiangling',
    rarity: 4,
    weapon: 'Polearm',
    element: 'Pyro',
  },
  {
    name: 'Xiao',
    rarity: 5,
    weapon: 'Polearm',
    element: 'Anemo',
  },
  {
    name: 'Xingqiu',
    rarity: 4,
    weapon: 'Sword',
    element: 'Hydro',
  },
  {
    name: 'Xinyan',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Pyro',
  },
  {
    name: 'Yanfei',
    rarity: 4,
    weapon: 'Catalyst',
    element: 'Pyro',
  },
  {
    name: 'Yoimiya',
    tier: 'C',
    rarity: 5,
    weapon: 'Bow',
    element: 'Pyro',
  },
  {
    name: 'Yun Jin',
    rarity: 4,
    weapon: 'Polearm',
    element: 'Geo',
  },
  {
    name: 'Zhongli',
    rarity: 5,
    weapon: 'Polearm',
    element: 'Geo',
  },
  {
    name: 'Ayato',
    rarity: 5,
    weapon: 'Sword',
    element: 'Hydro',
  },
]

export default characters
