export const characters = [
  {
    id: 'albedo',
    name: 'Albedo',
    rarity: 5,
    weapon: 'Sword',
    element: 'Geo',
  },
  {
    id: 'aloy',
    name: 'Aloy',
    rarity: 5,
    weapon: 'Bow',
    element: 'Cryo',
  },
  {
    id: 'amber',
    name: 'Amber',
    rarity: 4,
    weapon: 'Bow',
    element: 'Pyro',
  },
  {
    id: 'ayaka',
    name: 'Ayaka',
    rarity: 5,
    weapon: 'Sword',
    element: 'Cryo',
  },
  {
    id: 'barbara',
    name: 'Barbara',
    rarity: 4,
    weapon: 'Catalyst',
    element: 'Hydro',
  },
  {
    id: 'beidou',
    name: 'Beidou',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Electro',
  },
  {
    id: 'bennett',
    name: 'Bennett',
    rarity: 4,
    weapon: 'Sword',
    element: 'Pyro',
  },
  {
    id: 'chongyun',
    name: 'Chongyun',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Cryo',
  },
  {
    id: 'diluc',
    name: 'Diluc',
    rarity: 5,
    weapon: 'Claymore',
    element: 'Pyro',
  },
  {
    id: 'diona',
    name: 'Diona',
    rarity: 4,
    weapon: 'Bow',
    element: 'Cryo',
  },
  {
    id: 'eula',
    name: 'Eula',
    rarity: 5,
    weapon: 'Claymore',
    element: 'Cryo',
  },
  {
    id: 'fischl',
    name: 'Fischl',
    rarity: 4,
    weapon: 'Bow',
    element: 'Electro',
  },
  {
    id: 'ganyu',
    name: 'Ganyu',
    rarity: 5,
    weapon: 'Bow',
    element: 'Cryo',
  },
  {
    id: 'gorou',
    name: 'Gorou',
    rarity: 4,
    weapon: 'Bow',
    element: 'Geo',
  },
  {
    id: 'hutao',
    name: 'Hu Tao',
    rarity: 5,
    weapon: 'Polearm',
    element: 'Pyro',
  },
  {
    id: 'itto',
    name: 'Itto',
    rarity: 5,
    weapon: 'Claymore',
    element: 'Geo',
  },
  {
    id: 'jean',
    name: 'Jean',
    rarity: 5,
    weapon: 'Sword',
    element: 'Anemo',
  },
  {
    id: 'kaeya',
    name: 'Kaeya',
    rarity: 4,
    weapon: 'Sword',
    element: 'Cryo',
  },
  {
    id: 'kazuha',
    name: 'Kazuha',
    rarity: 5,
    weapon: 'Sword',
    element: 'Anemo',
  },
  {
    id: 'keqing',
    name: 'Keqing',
    rarity: 5,
    weapon: 'Sword',
    element: 'Electro',
  },
  {
    id: 'klee',
    name: 'Klee',
    rarity: 5,
    weapon: 'Catalyst',
    element: 'Pyro',
  },
  {
    id: 'kokomi',
    name: 'Kokomi',
    rarity: 5,
    weapon: 'Catalyst',
    element: 'Hydro',
  },
  {
    id: 'lisa',
    name: 'Lisa',
    rarity: 4,
    weapon: 'Catalyst',
    element: 'Electro',
  },
  {
    id: 'yae',
    name: 'Yae Miko',
    rarity: 5,
    weapon: 'Catalyst',
    element: 'Electro',
  },
  {
    id: 'mona',
    name: 'Mona',
    rarity: 5,
    weapon: 'Catalyst',
    element: 'Hydro',
  },
  {
    id: 'ningguang',
    name: 'Ningguang',
    rarity: 4,
    weapon: 'Catalyst',
    element: 'Geo',
  },
  {
    id: 'noelle',
    name: 'Noelle',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Geo',
  },
  {
    id: 'qiqi',
    name: 'Qiqi',
    rarity: 5,
    weapon: 'Sword',
    element: 'Cryo',
  },
  {
    id: 'razor',
    name: 'Razor',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Electro',
  },
  {
    id: 'rosaria',
    name: 'Rosaria',
    rarity: 4,
    weapon: 'Polearm',
    element: 'Cryo',
  },
  {
    id: 'sara',
    name: 'Sara',
    rarity: 4,
    weapon: 'Bow',
    element: 'Electro',
  },
  {
    id: 'sayu',
    name: 'Sayu',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Anemo',
  },
  {
    id: 'shenhe',
    name: 'Shenhe',
    rarity: 5,
    weapon: 'Polearm',
    element: 'Cryo',
  },
  {
    id: 'shogun',
    name: 'Shogun',
    rarity: 5,
    weapon: 'Polearm',
    element: 'Electro',
  },
  {
    id: 'sucrose',
    name: 'Sucrose',
    rarity: 4,
    weapon: 'Catalyst',
    element: 'Anemo',
  },
  {
    id: 'tartaglia',
    name: 'Tartaglia',
    rarity: 5,
    weapon: 'Bow',
    element: 'Hydro',
  },
  {
    id: 'thoma',
    name: 'Thoma',
    rarity: 4,
    weapon: 'Polearm',
    element: 'Pyro',
  },
  {
    id: 'anemo-traveler',
    name: 'Traveler',
    rarity: 5,
    weapon: 'Sword',
    element: 'Anemo',
  },
  {
    id: 'geo-traveler',
    name: 'Traveler',
    rarity: 5,
    weapon: 'Sword',
    element: 'Geo',
  },
  {
    id: 'electro-traveler',
    name: 'Traveler',
    rarity: 5,
    weapon: 'Sword',
    element: 'Electro',
  },
  {
    id: 'venti',
    name: 'Venti',
    rarity: 5,
    weapon: 'Bow',
    element: 'Anemo',
  },
  {
    id: 'xiangling',
    name: 'Xiangling',
    rarity: 4,
    weapon: 'Polearm',
    element: 'Pyro',
  },
  {
    id: 'xiao',
    name: 'Xiao',
    rarity: 5,
    weapon: 'Polearm',
    element: 'Anemo',
  },
  {
    id: 'xingqiu',
    name: 'Xingqiu',
    rarity: 4,
    weapon: 'Sword',
    element: 'Hydro',
  },
  {
    id: 'xinyan',
    name: 'Xinyan',
    rarity: 4,
    weapon: 'Claymore',
    element: 'Pyro',
  },
  {
    id: 'yanfei',
    name: 'Yanfei',
    rarity: 4,
    weapon: 'Catalyst',
    element: 'Pyro',
  },
  {
    id: 'yoimiya',
    name: 'Yoimiya',
    rarity: 5,
    weapon: 'Bow',
    element: 'Pyro',
  },
  {
    id: 'yunjin',
    name: 'Yun Jin',
    rarity: 4,
    weapon: 'Polearm',
    element: 'Geo',
  },
  {
    id: 'zhongli',
    name: 'Zhongli',
    rarity: 5,
    weapon: 'Polearm',
    element: 'Geo',
  },
  {
    id: 'ayato',
    name: 'Ayato',
    rarity: 5,
    weapon: 'Sword',
    element: 'Hydro',
  },
]

export default characters
